apiVersion: apps/v1
kind: Deployment
metadata:
  name: common-data-service
  namespace: ecf-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: common-data-service
  template:
    metadata:
      labels:
        app: common-data-service
    spec:
      containers:
      - name: common-data-service
        image: rayanemeyfr/ecf-common-data-service:latest
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: DB_PORT
        - name: DB_SCHEMA
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: DB_SCHEMA
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: DB_USER
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: DB_PASS
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: REDIS_PORT
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: REDIS_PASSWORD
        - name: ACTIVE_PROFILE
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: ACTIVE_PROFILE
        - name: PORT
          value: "9000"
        ports:
        - containerPort: 9000