apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: ecf-namespace
spec:
  selector:
    app: payment-service
  ports:
    - port: 9050       
      targetPort: 8080  
  type: ClusterIP