apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: ecf-namespace
type: Opaque
data:
  DB_HOST: bXlzcWw=
  DB_PORT: MzMwNg==
  DB_SCHEMA: ZWNvbW1lcmNlX2FwcF9kYXRhYmFzZQ==
  DB_USER: bXlzcWx1c2Vy
  DB_PASS: bXlwYXNz
  REDIS_HOST: cmVkaXM=
  REDIS_PORT: NjM3OQ==
  REDIS_PASSWORD: bXlwYXNz
  ACTIVE_PROFILE: ZGV2