apiVersion: v1
kind: Service
metadata:
  name: front-app-service
  namespace: ecf-namespace
spec:
  selector:
    app: front-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000